/***門診服務量***/
--修正處置人次ACC_CODE
--門急診醫師姓名皆使用 STAFF_NAME

WITH
    A
    AS
    (
        SELECT
            HIS_RPATREG.DATESEQ,
            CONVERT(DATE,HIS_RPATREG.CLN_DATE,112) AS CLN_DATE,
            HIS_RPATREG.CLN_TYPE,
            (SELECT DESP
            FROM HIS_HARD_CODE
            WHERE CODE = HIS_RPATREG.CLN_TYPE AND COLUMN_ID = 'CLN_TYPE' AND TABLE_ID = 'CLN_TYPE') AS CLN_NAME, --子查詢 hardcode 查詢來源別中文
            HIS_RPATREG.CHECK_TYPE,--急診檢傷分類
            部門別,
            HIS_RPATREG.DIV_CODE,
            DIV_NAME,--病人科別中文
            主科別名稱,
            --門診醫師抓 DR_CODE，急診醫師抓 EXE_DOCTOR，將兩欄醫師人員代碼合併為一欄
            --若 DR_CODE 為醫師輪診且 EXE_DOCTOR 不為 NULL時，則抓取DR_CODE 的醫師呈現
            CASE 
      WHEN DR_CODE = '000COM' AND HIS_RPATREG.EXE_DOCTOR IS NOT NULL THEN HIS_RPATREG.EXE_DOCTOR
      ELSE DR_CODE
    END AS DR_CODE,
            HIS_RPATREG.INSU_TYPE,
            (SELECT DESP
            FROM HIS_HARD_CODE
            WHERE CODE = HIS_RPATREG.INSU_TYPE AND COLUMN_ID = 'INSU_TYPE' AND TABLE_ID = 'RPATREG') AS INSU_TYPE_NAME, --子查詢 hardcode 查詢身分別中文
            HIS_RPATREG.VIEW_TIME,
            HIS_RPATREG.ER_DIV,
            (SELECT DESP
            FROM HIS_HARD_CODE
            WHERE CODE = HIS_RPATREG.ER_DIV AND COLUMN_ID = 'ER_DIV' AND TABLE_ID = 'RPATREG') AS ER_DIV_NAME, --子查詢 hardcode 查詢急診科別中文
            HIS_RPATREG.FV_RV,
            (SELECT DESP
            FROM HIS_HARD_CODE
            WHERE CODE = HIS_RPATREG.FV_RV AND COLUMN_ID = 'FV_RV' AND TABLE_ID = 'RPATREG') AS FV_RV_NAME, --子查詢 hardcode 查詢初複診中文
            HIS_RPATREG.APN,
            APN_NAME,
            HIS_RPATREG.TRANS_FLAG,
            HIS_RPATREG.HSP_CODE,
            HIS_RPATREG.CLN_CODE,
            HIS_RPATREG.REG_STATUS,
            (SELECT DESP
            FROM HIS_HARD_CODE
            WHERE CODE = HIS_RPATREG.REG_STATUS AND COLUMN_ID = 'REG_STATUS' AND TABLE_ID = 'RPATREG') AS REG_STATUS_NAME, --子查詢 hardcode 查詢狀況中文
            /***初診人次***/
            IIF(REG_STATUS  IN ('D', 'R' , 'P') and FV_RV in ('1')and HIS_RPATREG.CLN_CODE <> '00912D'and DOC_TYPE <> 'a',1,0) AS FV_NUM,
            /***門診服務量***/
            IIF(REG_STATUS  IN ('D', 'R' , 'P') and CLN_TYPE IN ('O', 'F', 'S', 'L', 'H', 'R', 'N'),1,0) AS SV_NUM,
            /***實際門診看醫師***/
            IIF(( HIS_RPATREG.CLN_TYPE IN ('O','N','F') or (HIS_RPATREG.CLN_TYPE='F' and HIS_RPATREG.DIV_CODE<>'6410' )  or (HIS_RPATREG.CLN_TYPE='F' and HIS_RPATREG.DIV_CODE='6410' and  exists (select 1 from HIS_DPATORD where HIS_DPATORD.DATESEQ=HIS_RPATREG.DATESEQ and rtrim(price_code) in
('051515', '051516', '051517', '051518'))))AND REG_STATUS  IN ('D', 'R' , 'P') and DOC_TYPE <>'a'AND CLN_CODE NOT IN ('CHR','CON','00912D'),1,0) AS RV_NUM,
            /***手術人次***/
            IIF(HIS_RPATREG.DATESEQ IN (SELECT HIS_DPATORD.DATESEQ FROM HIS_DPATORD WHERE CLN_TYPE IN ('O', 'F', 'S', 'L', 'H', 'R', 'N','E') AND ACC_CODE = '85' and REG_STATUS  IN ('D', 'R' , 'P')),1,0) AS OR_NUM,
            /***急診人次(計次用)***/
            IIF(REG_STATUS  IN ('D', 'R' , 'P') AND CLN_TYPE='E',1,0) AS EMER_NUM,
            /***急診人次(分類用)***/
            IIF(REG_STATUS  IN ('D', 'R' , 'P') AND CLN_TYPE='E','1','0') AS EMER_TYPE,
            /***檢查人次***/
            IIF(
(SELECT COUNT(*) FROM HIS_DPATORD 
WHERE HIS_DPATORD.DATESEQ = HIS_RPATREG.DATESEQ 
AND CLN_TYPE IN ('O', 'F', 'S', 'L', 'H', 'R', 'N','E') 
AND ACC_CODE IN('30', '31', '32', '33', '34', '36', '37', '42', '47', '48', '49', '50', '51', '52', '53') 
AND REG_STATUS  IN ('D', 'R' , 'P')) > 0,
(SELECT COUNT(*) FROM HIS_DPATORD 
WHERE HIS_DPATORD.DATESEQ = HIS_RPATREG.DATESEQ 
AND CLN_TYPE IN ('O', 'F', 'S', 'L', 'H', 'R', 'N','E') 
AND ACC_CODE IN('30', '31', '32', '33', '34', '36', '37', '42', '47', '48', '49', '50', '51', '52', '53') 
AND REG_STATUS  IN ('D', 'R' , 'P'))
,0) AS CHECK_NUM,
            /***處置人次***/
            IIF(
(SELECT COUNT(*) FROM HIS_DPATORD
WHERE HIS_DPATORD.DATESEQ = HIS_RPATREG.DATESEQ 
AND CLN_TYPE IN ('O', 'F', 'S', 'L', 'H', 'R', 'N','E') 
AND ACC_CODE IN   ('77','107','106','14','96','94','93','92','91','90','83','82','80','78','76','75','73','72','71','70','68','67','65','64','63','62')
AND REG_STATUS  IN ('D', 'R' , 'P')) >0,
(SELECT COUNT(*) FROM HIS_DPATORD
WHERE HIS_DPATORD.DATESEQ = HIS_RPATREG.DATESEQ 
AND CLN_TYPE IN ('O', 'F', 'S', 'L', 'H', 'R', 'N','E') 
AND ACC_CODE IN   ('77','107','106','14','96','94','93','92','91','90','83','82','80','78','76','75','73','72','71','70','68','67','65','64','63','62')
AND REG_STATUS  IN ('D', 'R' , 'P'))
,0) AS DISPOSITION_NUM,
            /***區域代碼_人口學分析地圖記人次用***/
            HIS_CCHART.AREA_CODE,
            (SELECT AREA_NAME
            FROM AREA_CODE_CHI
            WHERE AREA_CODE_CHI.AREA_CODE = HIS_CCHART.AREA_CODE) AS AREA_NAME,
            HIS_CCHART.SEX,
            (SELECT DESP
            FROM HIS_HARD_CODE
            WHERE CODE = HIS_CCHART.SEX AND COLUMN_ID = 'SEX' AND TABLE_ID = 'CCHART') AS  SEX_NAME, --子查詢 hardcode 查詢性別中文
            DATEDIFF(YEAR,CONVERT(DATETIME,HIS_CCHART.BIRTH_DATE,112),GETDATE()) AS AGE,
            CASE
WHEN DATEDIFF(YEAR,CONVERT(DATETIME,HIS_CCHART.BIRTH_DATE,112),GETDATE())<10 THEN '0-10歲'
WHEN DATEDIFF(YEAR,CONVERT(DATETIME,HIS_CCHART.BIRTH_DATE,112),GETDATE())<20 THEN '10-20歲'
WHEN DATEDIFF(YEAR,CONVERT(DATETIME,HIS_CCHART.BIRTH_DATE,112),GETDATE())<30 THEN '20-30歲'
WHEN DATEDIFF(YEAR,CONVERT(DATETIME,HIS_CCHART.BIRTH_DATE,112),GETDATE())<40 THEN '30-40歲'
WHEN DATEDIFF(YEAR,CONVERT(DATETIME,HIS_CCHART.BIRTH_DATE,112),GETDATE())<50 THEN '40-50歲'
WHEN DATEDIFF(YEAR,CONVERT(DATETIME,HIS_CCHART.BIRTH_DATE,112),GETDATE())<60 THEN '50-60歲'
WHEN DATEDIFF(YEAR,CONVERT(DATETIME,HIS_CCHART.BIRTH_DATE,112),GETDATE())<70 THEN '60-70歲'
WHEN DATEDIFF(YEAR,CONVERT(DATETIME,HIS_CCHART.BIRTH_DATE,112),GETDATE())<80 THEN '70-80歲'
WHEN DATEDIFF(YEAR,CONVERT(DATETIME,HIS_CCHART.BIRTH_DATE,112),GETDATE())>80 THEN '80歲以上'
END AS AGE_RANGE,
            IIF(PRE_IPD_DATE IS NOT NULL,1,0) AS PRE_OPD_TRANS_IPD_OR_NOT,
            PRE_IPD_DATE,
            SUBSTRING(IPD_DATESEQ,1,8) AS IN_IPD_DATE,
            IIF(SUBSTRING(IPD_DATESEQ,1,8) IS NOT NULL,1,0) AS IN_OPD_TRANS_IPD_OR_NOT,
            CARE_PLAN,
            COUNT(1) AS PT_NUM
        FROM HIS_RPATREG
            LEFT JOIN HIS_OPD_TRANS_IPD ON HIS_RPATREG.DATESEQ = HIS_OPD_TRANS_IPD.DATESEQ
            LEFT JOIN DIV_CODE_CHI ON HIS_RPATREG.DIV_CODE = DIV_CODE_CHI.DIV_CODE
            LEFT JOIN HIS_CCHART ON HIS_RPATREG.CHT_ID = HIS_CCHART.CHT_ID
            LEFT JOIN APN_TAB ON HIS_RPATREG.APN = APN_TAB.APN
        WHERE 
--如果今天是本月1號，顯示上個月的完整數據
(
(DAY(GETDATE()) = 1
            AND CLN_DATE BETWEEN CONVERT(VARCHAR, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) -1, 0), 112) AND CONVERT(VARCHAR, EOMONTH(GETDATE(), -1) , 112)
            OR
            --如果今天不是本月1號，則顯示本月的資料
            (DAY(GETDATE()) <> 1
            AND CLN_DATE BETWEEN CONVERT(VARCHAR, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0), 112) and CONVERT(VARCHAR, EOMONTH(GETDATE()), 112)))
)
            AND HIS_RPATREG.CLN_TYPE IN ('O', 'F', 'S', 'L', 'H', 'R', 'N', 'E')
        GROUP BY HIS_RPATREG.DATESEQ,HIS_RPATREG.CLN_DATE,HIS_RPATREG.CLN_TYPE,HIS_RPATREG.DIV_CODE,部門別,主科別名稱,HIS_RPATREG.DIV_CODE,HIS_RPATREG.INSU_TYPE,HIS_RPATREG.CLN_CODE,HIS_RPATREG.DOC_TYPE,HIS_RPATREG.ER_CHK_FLAG,HIS_RPATREG.REG_STATUS,HIS_RPATREG.FV_RV,HIS_CCHART.SEX,HIS_CCHART.AREA_CODE,HIS_CCHART.BIRTH_DATE,HIS_RPATREG.KIND_REMEDY,DIV_NAME,HIS_RPATREG.DR_CODE,HIS_RPATREG.EXE_DOCTOR,HIS_RPATREG.ER_DIV,HIS_RPATREG.APN,HIS_RPATREG.TRANS_FLAG,HIS_RPATREG.HSP_CODE,HIS_RPATREG.CHECK_TYPE,HIS_OPD_TRANS_IPD.PRE_IPD_DATE,HIS_OPD_TRANS_IPD.IPD_DATESEQ,HIS_OPD_TRANS_IPD.CARE_PLAN,HIS_RPATREG.VIEW_TIME,APN_NAME
    )
SELECT
    DATESEQ, CLN_DATE, CLN_TYPE, CLN_NAME, CHECK_TYPE, 部門別, A.DIV_CODE, DIV_NAME, 主科別名稱, STAFF_NAME, INSU_TYPE_NAME,
    VIEW_TIME, ER_DIV, ER_DIV_NAME, FV_RV, FV_RV_NAME, APN, APN_NAME, TRANS_FLAG, HSP_CODE, CLN_CODE, REG_STATUS, REG_STATUS_NAME,
    REG_SY_NUM, REG_CANCEL_NUM, FV_NUM, SV_NUM, RV_NUM, OR_NUM, EMER_NUM, EMER_TYPE, CHECK_NUM, DISPOSITION_NUM, AREA_CODE,
    AREA_NAME, SEX, SEX_NAME, AGE, AGE_RANGE, PRE_OPD_TRANS_IPD_OR_NOT, PRE_IPD_DATE, IN_IPD_DATE, IN_OPD_TRANS_IPD_OR_NOT,
    CARE_PLAN, PT_NUM
FROM A
    LEFT JOIN HIS_MSTAFF ON A.DR_CODE = HIS_MSTAFF.STAFF_CODE
WHERE 
--如果今天是本月1號，顯示上個月的完整數據
(
(DAY(GETDATE()) = 1
    AND CLN_DATE BETWEEN CONVERT(VARCHAR, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) -1, 0), 112) AND CONVERT(VARCHAR, EOMONTH(GETDATE(), -1) , 112)
    OR
    --如果今天不是本月1號，則顯示本月的資料
    (DAY(GETDATE()) <> 1
    AND CLN_DATE BETWEEN CONVERT(VARCHAR, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0), 112) and CONVERT(VARCHAR, EOMONTH(GETDATE()), 112)))
)


